# Generated by Django 3.2 on 2022-07-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
