# Generated by Django 3.2 on 2022-07-05 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_books_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallcategory',
            name='large_category',
            field=models.ForeignKey(default='---------', on_delete=django.db.models.deletion.CASCADE, to='book_app.largecategory'),
        ),
    ]
