# Generated by Django 3.2 on 2022-07-05 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_alter_smallcategory_large_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallcategory',
            name='large_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.largecategory'),
        ),
    ]
